services:
  db:
    image: postgres:17
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  minio:
    image: minio/minio:latest
    container_name: minio
    volumes:
      - minio-data:/data
    env_file:
      - .env
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

  migrations:
    build: ./
    restart: on-failure
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db
    command: [ "python", "-m", "alembic", "upgrade", "head" ]

  app:
    build: ./
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    ports:
      - "127.0.0.1:8000:8000"
    command: >
      sh -c "python -m uvicorn dah.main:get_app --factory --host 0.0.0.0"
    depends_on:
      - minio
      - migrations


volumes:
  minio-data:
  postgres-data: